- name: Install and Run nginx
  hosts: web
  become: yes   #-b
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
