- name: Variables
  hosts:  local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: "Please Enter Course name"
    private: false
  - name: DURATION
    prompt: "please enter Duration"
    private: false
  - name: TRAINER
    prompt: "Please enter trainer name"
    private: false
  tasks:
  - name: Print Variables
    ansible.builtin.debug:
      msg: "These Course is {{COURSE}} , Duration is {{DURATION}} , Trainer is {{TRAINER}}"