- name: Variables
  hosts:  local
  connection: local
  vars:
    GREET: "Play Level"
  # vars_files:
  # - vars.yaml
  vars_prompt:
  - name: GREET
    prompt: "Enter Greet"
    private: false
  tasks:
  - name: Task
    # vars:
    #   GREET: "Task Level"
    ansible.builtin.debug:
      msg: "Print Greet: {{GREET}}"