- name: Variables
  hosts:  local
  connection: local
  vars_prompt:
    - name: NO
      prompt: "Enter Number"
      private: false
  tasks:
  - name: Print No greater than
    ansible.builtin.debug:
      msg: "Given Number {{NO}} is Greater than 10"
    when: NO >= 10
  - name: Print No less than 10
    ansible.builtin.debug:
      msg: "Given Number {{NO}} is less than 10"
    when: NO <= 10