- name: Variables
  hosts:  local
  connection: local
  vars:
    NUM: 10
  tasks:
  - name: Print No greater than
    ansible.builtin.debug:
      msg: "Given Number {{NUM}} is Greater than 10"
    when: NUM >= 10
  - name: Print No less than 10
    ansible.builtin.debug:
      msg: "Given Number {{NUM}} is less than 10"
    when: NUM <= 10