- name: "install nginx"
  hosts:  web
  become: yes
  tasks:
  - name: Install os in RHEL
    ansible.builtin.dnf:
      name: nginx
      state:  installed
    when: ansible_os_family == "RedHat"

  - name: Install os in Ubuntu
    ansible.builtin.apt:
      name: nginx
      state:  installed
    when: ansible_os_family == "Debian"