- name: Variables
  hosts:  local
  connection: local
  tasks:
  - name: Print default
    ansible.builtin.debug:
      msg: "course is {{ COURSE | default('devOps') }}"
  - name: print split
    vars:
      fruits: "apple, banana, cherry"
    ansible.builtin.debug:
      msg: "Fruits are {{fruits | split(',') }}"
  - name: Print toUpper
    vars:
      name: Sivakumar
    ansible.builtin.debug:
      msg: "TO Upper is {{ name | upper }}"
  - name: Print tolower
    vars:
      name: Sivakumar
    ansible.builtin.debug:
      msg: "TO Upper is {{ name | lower }}"
  - name: Print maxi
    vars:
      name: [100,200,300,500,400,150,325,55]
    ansible.builtin.debug:
      msg: "TO maxi is {{ name | max }}"
  - name: Print mini
    vars:
      name: [100,200,300,500,400,150,325,55]
    ansible.builtin.debug:
      msg: "TO mini is {{ name | min }}"

