- name: Create ec2 instances and r53 Roles
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id:  sg-0cf2573541701f747
    subnet_id:  subnet-05087e067a86d45dc
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install python lib
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info